export const SET_LOCATIONS = "SET_LOCATION";
export const SET_TIMES = "GET_TIMES";
export const SET_ORIENTATION = "SET_ORIENTATION";

export const FETCH_TIMES_REQUEST = "FETCH_TIMES_REQUEST";
export const FETCH_TIMES_SUCCESS = "FETCH_TIMES_SUCCESS";
export const FETCH_TIMES_FAILURE = "FETCH_TIMES_FAILURE";

export const FETCH_LOCATIONS_REQUEST = "FETCH_LOCATIONS_REQUEST";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";

export const FETCH_ORIENTATION_REQUEST = "FETCH_ORIENTATION_REQUEST";
export const FETCH_ORIENTATION_SUCCESS = "FETCH_ORIENTATION_SUCCESS";
export const FETCH_ORIENTATION_FAILURE = "FETCH_ORIENTATION_FAILURE";
